//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.15 at 01:43:49 AM EET 
//


package com.telesens.afanasiev.dao.impl.jaxb.schemes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.telesens.afanasiev.dao.impl.jaxb.schemes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.telesens.afanasiev.dao.impl.jaxb.schemes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RunTimetable }
     * 
     */
    public RunTimetable createRunTimetable() {
        return new RunTimetable();
    }

    /**
     * Create an instance of {@link RunTimetable.Task }
     * 
     */
    public RunTimetable.Task createRunTimetableTask() {
        return new RunTimetable.Task();
    }

}
