//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.14 at 06:18:35 AM EET 
//


package com.telesens.afanasiev.dao.impl.jaxb.schemes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="targets">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="target" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute ref="{}id use="required""/>
 *                           &lt;attribute name="stationId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="factor" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tasks">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="task" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="linkTarget" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="targetId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute ref="{}id use="required""/>
 *                           &lt;attribute name="stationId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                           &lt;attribute name="timeFrom" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="passCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="minutesLimitWaiting" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "targets",
    "tasks"
})
@XmlRootElement(name = "passGenRules")
public class PassGenRules {

    @XmlElement(required = true)
    protected PassGenRules.Targets targets;
    @XmlElement(required = true)
    protected PassGenRules.Tasks tasks;

    /**
     * Gets the value of the targets property.
     * 
     * @return
     *     possible object is
     *     {@link PassGenRules.Targets }
     *     
     */
    public PassGenRules.Targets getTargets() {
        return targets;
    }

    /**
     * Sets the value of the targets property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassGenRules.Targets }
     *     
     */
    public void setTargets(PassGenRules.Targets value) {
        this.targets = value;
    }

    /**
     * Gets the value of the tasks property.
     * 
     * @return
     *     possible object is
     *     {@link PassGenRules.Tasks }
     *     
     */
    public PassGenRules.Tasks getTasks() {
        return tasks;
    }

    /**
     * Sets the value of the tasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassGenRules.Tasks }
     *     
     */
    public void setTasks(PassGenRules.Tasks value) {
        this.tasks = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="target" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute ref="{}id use="required""/>
     *                 &lt;attribute name="stationId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="factor" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "target"
    })
    public static class Targets {

        @XmlElement(required = true)
        protected List<PassGenRules.Targets.Target> target;

        /**
         * Gets the value of the target property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the target property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTarget().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PassGenRules.Targets.Target }
         * 
         * 
         */
        public List<PassGenRules.Targets.Target> getTarget() {
            if (target == null) {
                target = new ArrayList<PassGenRules.Targets.Target>();
            }
            return this.target;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute ref="{}id use="required""/>
         *       &lt;attribute name="stationId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="factor" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Target {

            @XmlAttribute(name = "id", required = true)
            protected long id;
            @XmlAttribute(name = "stationId", required = true)
            protected long stationId;
            @XmlAttribute(name = "factor", required = true)
            protected int factor;

            /**
             * Gets the value of the id property.
             * 
             */
            public long getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(long value) {
                this.id = value;
            }

            /**
             * Gets the value of the stationId property.
             * 
             */
            public long getStationId() {
                return stationId;
            }

            /**
             * Sets the value of the stationId property.
             * 
             */
            public void setStationId(long value) {
                this.stationId = value;
            }

            /**
             * Gets the value of the factor property.
             * 
             */
            public int getFactor() {
                return factor;
            }

            /**
             * Sets the value of the factor property.
             * 
             */
            public void setFactor(int value) {
                this.factor = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="task" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="linkTarget" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="targetId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute ref="{}id use="required""/>
     *                 &lt;attribute name="stationId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *                 &lt;attribute name="timeFrom" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                 &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="passCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="minutesLimitWaiting" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "task"
    })
    public static class Tasks {

        @XmlElement(required = true)
        protected List<PassGenRules.Tasks.Task> task;

        /**
         * Gets the value of the task property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the task property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTask().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PassGenRules.Tasks.Task }
         * 
         * 
         */
        public List<PassGenRules.Tasks.Task> getTask() {
            if (task == null) {
                task = new ArrayList<PassGenRules.Tasks.Task>();
            }
            return this.task;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="linkTarget" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="targetId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute ref="{}id use="required""/>
         *       &lt;attribute name="stationId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
         *       &lt;attribute name="timeFrom" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *       &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="passCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="minutesLimitWaiting" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "linkTarget"
        })
        public static class Task {

            @XmlElement(required = true)
            protected List<PassGenRules.Tasks.Task.LinkTarget> linkTarget;
            @XmlAttribute(name = "id", required = true)
            protected long id;
            @XmlAttribute(name = "stationId", required = true)
            protected long stationId;
            @XmlAttribute(name = "timeFrom", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar timeFrom;
            @XmlAttribute(name = "duration", required = true)
            protected int duration;
            @XmlAttribute(name = "passCount", required = true)
            protected int passCount;
            @XmlAttribute(name = "minutesLimitWaiting", required = true)
            protected int minutesLimitWaiting;

            /**
             * Gets the value of the linkTarget property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the linkTarget property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLinkTarget().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PassGenRules.Tasks.Task.LinkTarget }
             * 
             * 
             */
            public List<PassGenRules.Tasks.Task.LinkTarget> getLinkTarget() {
                if (linkTarget == null) {
                    linkTarget = new ArrayList<PassGenRules.Tasks.Task.LinkTarget>();
                }
                return this.linkTarget;
            }

            /**
             * Gets the value of the id property.
             * 
             */
            public long getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(long value) {
                this.id = value;
            }

            /**
             * Gets the value of the stationId property.
             * 
             */
            public long getStationId() {
                return stationId;
            }

            /**
             * Sets the value of the stationId property.
             * 
             */
            public void setStationId(long value) {
                this.stationId = value;
            }

            /**
             * Gets the value of the timeFrom property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getTimeFrom() {
                return timeFrom;
            }

            /**
             * Sets the value of the timeFrom property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTimeFrom(XMLGregorianCalendar value) {
                this.timeFrom = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             */
            public int getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             */
            public void setDuration(int value) {
                this.duration = value;
            }

            /**
             * Gets the value of the passCount property.
             * 
             */
            public int getPassCount() {
                return passCount;
            }

            /**
             * Sets the value of the passCount property.
             * 
             */
            public void setPassCount(int value) {
                this.passCount = value;
            }

            /**
             * Gets the value of the minutesLimitWaiting property.
             * 
             */
            public int getMinutesLimitWaiting() {
                return minutesLimitWaiting;
            }

            /**
             * Sets the value of the minutesLimitWaiting property.
             * 
             */
            public void setMinutesLimitWaiting(int value) {
                this.minutesLimitWaiting = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="targetId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class LinkTarget {

                @XmlAttribute(name = "targetId", required = true)
                protected long targetId;

                /**
                 * Gets the value of the targetId property.
                 * 
                 */
                public long getTargetId() {
                    return targetId;
                }

                /**
                 * Sets the value of the targetId property.
                 * 
                 */
                public void setTargetId(long value) {
                    this.targetId = value;
                }

            }

        }

    }

}
