//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.15 at 01:43:49 AM EET 
//


package com.telesens.afanasiev.dao.impl.jaxb.schemes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="task" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="idRoute" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="timeStart" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="breakForwardDuration" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *                 &lt;attribute name="breakBackDuration" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "task"
})
@XmlRootElement(name = "runTimetable")
public class RunTimetable {

    @XmlElement(required = true)
    protected List<RunTimetable.Task> task;

    /**
     * Gets the value of the task property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the task property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTask().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RunTimetable.Task }
     * 
     * 
     */
    public List<RunTimetable.Task> getTask() {
        if (task == null) {
            task = new ArrayList<RunTimetable.Task>();
        }
        return this.task;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="idRoute" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="timeStart" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="breakForwardDuration" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *       &lt;attribute name="breakBackDuration" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Task {

        @XmlAttribute(name = "id", required = true)
        protected long id;
        @XmlAttribute(name = "idRoute", required = true)
        protected long idRoute;
        @XmlAttribute(name = "timeStart", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar timeStart;
        @XmlAttribute(name = "breakForwardDuration")
        protected Integer breakForwardDuration;
        @XmlAttribute(name = "breakBackDuration")
        protected Integer breakBackDuration;

        /**
         * Gets the value of the id property.
         * 
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(long value) {
            this.id = value;
        }

        /**
         * Gets the value of the idRoute property.
         * 
         */
        public long getRouteId() {
            return idRoute;
        }

        /**
         * Sets the value of the idRoute property.
         * 
         */
        public void setIdRoute(long value) {
            this.idRoute = value;
        }

        /**
         * Gets the value of the timeStart property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTimeStart() {
            return timeStart;
        }

        /**
         * Sets the value of the timeStart property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTimeStart(XMLGregorianCalendar value) {
            this.timeStart = value;
        }

        /**
         * Gets the value of the breakForwardDuration property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getBreakForwardDuration() {
            if (breakForwardDuration == null) {
                return  0;
            } else {
                return breakForwardDuration;
            }
        }

        /**
         * Sets the value of the breakForwardDuration property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBreakForwardDuration(Integer value) {
            this.breakForwardDuration = value;
        }

        /**
         * Gets the value of the breakBackDuration property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getBreakBackDuration() {
            if (breakBackDuration == null) {
                return  0;
            } else {
                return breakBackDuration;
            }
        }

        /**
         * Sets the value of the breakBackDuration property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBreakBackDuration(Integer value) {
            this.breakBackDuration = value;
        }

    }

}
