//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.11 at 12:33:51 AM EET 
//


package com.telesens.afanasiev.logs.shemes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.telesens.afanasiev.jaxb.logs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.telesens.afanasiev.jaxb.logs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Stations }
     * 
     */
    public Stations createStations() {
        return new Stations();
    }

    /**
     * Create an instance of {@link Stations.Log }
     * 
     */
    public Stations.Log createStationsLog() {
        return new Stations.Log();
    }

}
