//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.11 at 12:33:39 AM EET 
//


package com.telesens.afanasiev.jaxb.schemes.log;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="log" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="passengerId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="stationId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="busNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="timeComeIn" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="timeGoOut" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "log"
})
@XmlRootElement(name = "passengers")
public class Passengers {

    @XmlElement(required = true)
    protected List<Passengers.Log> log;

    /**
     * Gets the value of the log property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the log property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLog().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Passengers.Log }
     * 
     * 
     */
    public List<Passengers.Log> getLog() {
        if (log == null) {
            log = new ArrayList<Passengers.Log>();
        }
        return this.log;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="passengerId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="stationId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="busNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="timeComeIn" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="timeGoOut" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Log {

        @XmlAttribute(name = "passengerId", required = true)
        protected long passengerId;
        @XmlAttribute(name = "stationId", required = true)
        protected long stationId;
        @XmlAttribute(name = "busNumber", required = true)
        protected String busNumber;
        @XmlAttribute(name = "timeComeIn", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar timeComeIn;
        @XmlAttribute(name = "timeGoOut", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar timeGoOut;

        /**
         * Gets the value of the passengerId property.
         * 
         */
        public long getPassengerId() {
            return passengerId;
        }

        /**
         * Sets the value of the passengerId property.
         * 
         */
        public void setPassengerId(long value) {
            this.passengerId = value;
        }

        /**
         * Gets the value of the stationId property.
         * 
         */
        public long getStationId() {
            return stationId;
        }

        /**
         * Sets the value of the stationId property.
         * 
         */
        public void setStationId(long value) {
            this.stationId = value;
        }

        /**
         * Gets the value of the busNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBusNumber() {
            return busNumber;
        }

        /**
         * Sets the value of the busNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBusNumber(String value) {
            this.busNumber = value;
        }

        /**
         * Gets the value of the timeComeIn property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTimeComeIn() {
            return timeComeIn;
        }

        /**
         * Sets the value of the timeComeIn property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTimeComeIn(XMLGregorianCalendar value) {
            this.timeComeIn = value;
        }

        /**
         * Gets the value of the timeGoOut property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTimeGoOut() {
            return timeGoOut;
        }

        /**
         * Sets the value of the timeGoOut property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTimeGoOut(XMLGregorianCalendar value) {
            this.timeGoOut = value;
        }

    }

}
